# -*- coding: utf-8 -*-
"""diamond-visualisation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V0j7Jt0aQSc6Okb8lM3pTDU6zbgErqD_
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

diamond=pd.read_csv("diamonds.csv")

diamond

diamond.head()

fa=diamond.groupby('cut')[['carat','cut']].count();
fa

f,ax=plt.subplots(figsize=(2,5))
sns.boxplot(x='carat',y='cut',data=diamond)

f,ax=plt.subplots(figsize=(5,5))
sns.barplot(x='carat',y='cut',data=diamond)

f,a=plt.subplots(figsize=(7,5))
sns.violinplot(x='carat',y='cut',data=diamond,hue="cut")

sns.barplot(x='carat',y='cut',data=diamond)

sns.barplot(x='depth',y='color',data=diamond,hue='cut')

sns.barplot(x='table',y='cut',data=diamond)

s=diamond.loc[diamond['clarity']=="VS1",'depth'].dropna()
sns.distplot(s)

n_clarity=diamond.loc[diamond['clarity']!="VS1",'depth'].dropna()
sns.distplot(n_clarity)

sns.violinplot(x='carat',y='depth',data=diamond)

sns.swarmplot(x='carat',y='clarity',data=diamond.loc[0:100])

fig = plt.figure(figsize=(15,3))

plt.plot(diamond.depth, diamond.carat)
plt.xlabel('X Axis')
plt.ylabel('Y axis')
plt.title('Line Plot')
plt.suptitle('Sales Comaprison', size=20, y=1.03)

sns.stripplot(x='depth',y='cut',data=diamond.loc[:2500],jitter=False)

sns.jointplot(x='depth',y='table',data=diamond.loc[:2500])

sns.violinplot(x='depth',y='cut',data=diamond.loc[:2500],inner=None,color="grey")
sns.stripplot(x='depth',y='cut',data=diamond.loc[:2500],jitter=False)

sns.pairplot(diamond.loc[:2500])

sns.heatmap(diamond.corr(),vmin=-1, vmax=1, cmap='ocean')

sns.lmplot(x='depth',y='carat',data=diamond.loc[:2500],palette="Set2")
plt.show()

sns.lmplot(x='depth',y='carat',data=diamond.loc[:2500],palette="Set1",hue='clarity')
plt.show()

sns.pairplot(data=diamond.loc[:2500],hue='clarity')

